site_name: Tech Challenge
theme:
  name: material
dev_addr: 0.0.0.0:8000
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
