version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=lanchonete
      - POSTGRES_PASSWORD=password